import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import ScrollButton from "@/components/scrollButton";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fiducia Net | Tech Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${roboto.className} antialiased grid place-items-center bg-bgColor overflow-x-hidden  text-white min-h-screen w-screen`}
      >
        <main className="  max-w-screen-2xl ">
          <Navbar />
          {children}
          <Footer />
          <ScrollButton />
        </main>
      </body>
    </html>
  );
}
